### ISSUE TITLE
One Global Maze

### ISSUE THREAD

**Issue by wadefagen** [cs240-illinois/sp22_cs240_infinite-maze-shared#2]
Currently, the middleware does not "store" a maze -- if you open the maze in two windows, it simply generates two mazes generation history is entirely stored in the frontend.

Every new user (or returning user) should see the maze as it was generated in the past and engage with this existing maze instead of a new maze entirely.

**Comment by PeterYR** [comment]
Perhaps the middleware could store data about each 7x7 maze segment in a dict, something like:

```txt
{
  (0, 0): { "geom": <data> },
  (0, 1): {"geom": <data> },
  (-1, 0): {"geom": <data> }
}
```

Where the keys are row and column coordinates and the values are sub-dicts containing data about each 7x7 maze segment. All this data would have to be sent to the front-end to render the entire maze.

Dicts in Python are implemented with hash-maps, so we shouldn't have any runtime issues as the maze grows larger.

**Comment by PeterYR** [comment]
We could also implement #1 by allowing back-end MGs to respond with multiple maze segments and their respective coordinates, which would each be inserted into the middleware's maze data dict. The middleware would have to tell the MGs about the available space for new maze segments in its request.

**Comment by aarya-bhatia** [comment]
I was thinking that the middleware could maintain a tree-like structure where each region is a node and each node is divided into 4 parts- NW, SW, NE, SE. Then we could restrict the next maze to be generated within the bounds of some adjacent node and also prevent any overlaps of mazes of different sizes. (I have explained this in my week #2 doc)

**Comment by PeterYR** [comment]
I've been thinking about using the persistent maze system in #6 and informing an MG of which coordinates of the maze haven't been generated, and letting the MG send segments for multiple coordinates. For example:

- Frontend requests a maze segment for (20, 20). (Row 20, column 20)
- Middleware scans nearby segments, finds that (20, 20), (20, 21), (21, 20), and (21, 21) are all empty. This info is sent to an MG.
- MG decides to generate a 7x14 segment, returns a 7x7 segment marked for (20, 20) and another marked for (20, 21).
- Middleware stores these two segments, but only returns the (20, 20) segment to frontend. If the frontend then requests a segment for (20, 21), the other segment is returned. Alternatively, both 7x7 segments could be sent to the front-end to make the entire 7x14 segment appear at once.

Pros:

- Allows for non-rectangular segments
- Allows for non-contiguous segments, if desired for some reason
- Can be backwards-compatible with MGs designed for the current middleware (if the MG gives a 7x7 segment with no coordinate information, just default to (20, 20) in the example above).

Cons:

- Segment size will have to be restricted, otherwise we'd have to send huge packets to MGs about each available space for a 7x7 segment

**Comment by aarya-bhatia** [comment]
I like this approach of scanning the nearby areas. We basically need two pieces of information - the maximum width and height. I think we can add these parameters to the request to the MG and they can pick a width/height <= the given size. I believe you are using a variable called 'free space radius' in your code, is that the number of blocks your middleware checks for free space surrounding the current region?

**Comment by pcrain** [comment]
Thanks to @PeterYR, we've made progress towards storing the global maze state in a cache during run time. 🙂 Unfortunately, this still gets reset every time the server is closed down, so an even more permanent long-term solution would still be nice. I know @aarya-bhatia has already implemented storing the server list using MongoDB, so if either of you want work on long term storage for the maze state as well in case of a server shutdown or outage, that would be fantastic! (Or if anyone else would like to take a crack at it, also feel free. :smile: )

**Comment by aarya-bhatia** [comment]
@pcrain I'll try to implement persistent maze storage with MongoDB.  It is possible to use the Connection class in the GlobalMaze to connect to MongoDB. We can extend the connection class to include more functions for maze storage.

**Comment by wadefagen** [comment]
The latest server now has a persistent maze in the middleware, but it does not initialize the maze for a new user viewing the site -- I've tracked this on #22 since it's outside of the original scope here.

Amazing work on the persistent maze!! 🎉
